# Site settings
title: IBM Cloud 9
header-img: assets/img/austin-360-bridge.jpg
email: your-email@yourdomain.com
description: "Blogging platform for IBM's cloud division morale committee"
baseurl: ""
url: "http://ibmcloudnine.org"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
